### ISSUE TITLE
Plugin crashes by click on dropdown after GitExtension update 4.2.0.17591

### ISSUE THREAD

**Issue by AngieKadnar** [maraf/GitExtensions.SolutionRunner#36]
```
System.MissingMethodException: Method not found: 'GitUIPluginInterfaces.IProcess GitUIPluginInterfaces.IExecutable.Start(GitExtUtils.ArgumentString, Boolean, Boolean, Boolean, System.Text.Encoding, Boolean, Boolean)'.
   at GitExtensions.SolutionRunner.Services.GitSolutionFileProvider.GetListAsync(Boolean isTopLevelSearchOnly, Boolean includeWorkspaces)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitExtensions.SolutionRunner.Services.GitSolutionFileProvider.GetListAsync(Boolean isTopLevelSearchOnly, Boolean includeWorkspaces)
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.<>c__DisplayClass4_0.<<CreateBundleItemsAsync>b__0>d.MoveNext() in D:\Development\Maraf\GitExtensions.SolutionRunner\src\GitExtensions.SolutionRunner\UI\SolutionListMenuItem.cs:line 65
--- End of stack trace from previous location ---
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.CreateBundleItemsAsync(Boolean isTopLevelSearchedOnly, Boolean includeWorkspaces, HashSet`1 solutions) in D:\Development\Maraf\GitExtensions.SolutionRunner\src\GitExtensions.SolutionRunner\UI\SolutionListMenuItem.cs:line 61
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.OnDropDownOpening(Object sender, EventArgs e) in D:\Development\Maraf\GitExtensions.SolutionRunner\src\GitExtensions.SolutionRunner\UI\SolutionListMenuItem.cs:line 37
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

Error happens when you click on the dropdown of SolutionRunner

![image](https://github.com/maraf/GitExtensions.SolutionRunner/assets/45826225/c1d57379-661e-49ab-b38a-b1a81c116b0f)

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

**Comment by AngieKadnar** [comment]
There are no issues with the current version (version 7.0.0). I just had to uninstall the plugin and install the new version, because  i couldn't not simple update
